sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t besty4045/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true besty4045/react-test npm test

after_success:
  - docker build -t besty4045/multi-client ./client
  - docker build -t besty4045/multi-nginx ./nginx
  - docker build -t besty4045/multi-server ./server
  - docker build -t besty4045/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push besty4045/multi-client
  - docker push besty4045/multi-nginx
  - docker push besty4045/multi-server
  - docker push besty4045/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'eu-west-2'
  app: 'mpptools-test'
  env: 'Mpptoolstest-env'
  bucket: 'elasticbeanstalk-eu-west-2-108953339391'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY
